# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequest',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Rejected'), ('a', 'Accepted'), ('n', 'None')], default='n', max_length=1, null=True),
        ),
    ]
