# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0003_auto_20170514_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='rtn_status',
            field=models.CharField(blank=True, choices=[('r', 'Return'), ('c', 'Confimed'), ('f', 'Fake request')], max_length=1, null=True),
        ),
    ]
