# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0003_auto_20170511_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer',
            new_name='Author',
        ),
    ]
