# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0004_bookinstance_rtn_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylib.Genre'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='rtn_status',
            field=models.CharField(blank=True, choices=[('r', 'Return'), ('c', 'Confirm'), ('f', 'Fake request')], max_length=1, null=True),
        ),
    ]
