# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylib', '0004_auto_20170511_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
